version: "3.4"

services:
  pms-api:
    image: pms-api
    build:
      context: . # This points to current directory
      dockerfile: Dockerfile # Optional, only if not named 'Dockerfile'
    ports:
      - "5125:8080"
